[build]
command = "npm run build"
publish = "dist"

# Ignorar errores de TypeScript en el build
[build.environment]
CI = "false" # Esto evita que CI detenga el build por warnings

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
